### ISSUE TITLE
GUI not loading correct kernel 

### ISSUE THREAD

**Issue by apano** [Anaconda-Platform/nb_conda_kernels#114]
Hi, 
I am running jupyterhub on kubernetes. 
I currently have an image with conda version : 4.5.8. 
If from terminal run following: 
$conda create -n python3.6.6 python=3.6.6 ipykernel
$conda activate python3.6.6
$which pip 
/home/jovyan/conda-envs/python3.6.6/bin/pip

If from GUI I create a new notebook and run the same command I get the conda system path instead :
<img width="764" alt="pip-version" src="https://user-images.githubusercontent.com/8362818/48315964-616f0900-e5dd-11e8-888e-f437278ddefb.png">

If I run from terminal 
jupyter kernelspeclist
Available kernels:
  python3    /home/jovyan/conda-envs/python3.6.6/share/jupyter/kernels/python3
  python2    /usr/local/share/jupyter/kernels/python2
 
And the contents show
{
 "argv": [
  "/home/jovyan/conda-envs/python3.6.6/bin/python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python 3",
 "language": "python"
}

If I run the very same image in my computer I get the very same values in both GUI and Terminal. Do you have any hints on what else I could check? 
I already tried reinstalling conda/nb_conda/nb_conda_kernels, recreated all the environments several times. 
Thank you

**Comment by mcg1969** [comment]
I'm going to close this as stale, but please feel free to open a new issue if you can reproduce further.

Note however that `jupyter kernelspec list` _will not work_ with kernels discovered by the `nb_conda_kernels` package. The _only_ apps that work with this extension are `notebook` and `lab`. So it is not surprising that `jupyter kernelspec list` would fail to see your `python3.6.6` environment.
