### ISSUE TITLE
CalledProcessorError with recent conda for activation

### ISSUE THREAD

**Issue by metal3d** [Anaconda-Platform/nb_conda_kernels#116]
Hello, 
On Fedora 29, to activate a conda environment, we don't use "source activate ..." but "conda activate ..."

The problem is that after installation, I've got following error when I'm starting a notebook (jupyterlab) for a certain conda env:

```
subprocess.CalledProcessError: Command '['bash', '-c', '. "/usr/bin/activate" "/home/pafer/.conda/envs/mxnet-1.2.1" >/dev/null && printenv']' returned non-zero exit status 1.
```

To fixup the problem, for now, I created a `/usr/bin/activate` script that contains:

```
source /etc/profile.d/conda.sh
conda activate $@
```

But I wonder if there is a way to change the command without to set up that script manually.

Thanks for your help

**Comment by mcg1969** [comment]
I'm afraid I don't understand what's going on here. I'm well aware of the difference between `conda activate` and `source activate`. But in fact, if you look at the code for `<prefix>/bin/activate`, you'll find that it does exactly what your `/usr/bin/activate` script is doing.

And I also don't understand how _your_ `/usr/bin/activate` script is being called by `nb_conda_kernels`. It should't be. Did you modify the code somehow?

**Comment by metal3d** [comment]
The problem is simple. (I'm not english, maybe I didn't correctly explained)

Fedora 29 has got a conda package (`dnf install conda`) that has no `/usr/bin/activate` script (the reason is that "activate" word is too general and my collide with another tool). 
To activate the environment, we call `conda activate envname` and not `source activate`.

If I install `nb_conda_kernels`, launching jupyter results in an error saying that `activate` is not found. 

> And I also don't understand how _your_ `/usr/bin/activate` script is being called by `nb_conda_kernels`

The line I've put in the comment is from `nb_conda_kernels`, this is exactly the problem that I point: `nb_conda_kernels` calls "activate" script that is statically set to `/usr/bin/activate`. What I mean is that this script can be somewhere else and I don't have any possibility to set up nb_conda_kernels to use another "activation script path or command". 

So we need to be able to change the path or command to `activate` script.

At this time, I must create `/usr/bin/activate` script myself instead of being able to only change the command to "activate" the environment.

**Comment by mcg1969** [comment]
I'm going to close this because I'm not prepared to support an installation of `conda` that does not have the `$PREFIX/bin/activate` script; it is too important to the operation of the code. I am willing to entertain a PR that remains back-compatible with the existing approach however. For instance, perhaps the runner script could use `$PREFIX/etc/profile.d/conda.sh` if it exists.

**Comment by metal3d** [comment]
Sorry but I don't agree.

>  it is too important to the operation of the code

As I said, there are several ways to install conda, and the "activate" script is not the way to go for well installed package in Linux. This is a very bad pattern that Fedora or CentoOS fixed by making a regular "conda" RPM. As you said, `/etc/profile.d/conda.sh` is enough to have environment variables and "conda activate" can be used on any plateform (even if you installed Anaconda by hand, AFAIK).

Anyway, I really don't understand the problem to make the initialisation command as configurable.

To not make it configurable makes nb_conda_envs not working on many distributions that will, as Fedora or CentOS, fix the badly named/placed "activate" script...

**Comment by metal3d** [comment]
Hello,

The problem persists. 

When I use jupyter-lab with nb_conda_kernels, using a conda environment on Fedora 30, I see that error:
```
[I 14:08:47.779 LabApp] Kernel started: 71dac595-dca9-4ce5-ad27-26135ddce180
bash: /usr/bin/activate: No such file or directory
[I 14:08:50.781 LabApp] KernelRestarter: restarting kernel (1/5), new random ports
bash: /usr/bin/activate: No such file or directory
[I 14:08:53.789 LabApp] KernelRestarter: restarting kernel (2/5), new random ports
bash: /usr/bin/activate: No such file or directory
[I 14:08:56.806 LabApp] KernelRestarter: restarting kernel (3/5), new random ports
bash: /usr/bin/activate: No such file or directory
[I 14:08:59.817 LabApp] KernelRestarter: restarting kernel (4/5), new random ports
bash: /usr/bin/activate: No such file or directory
```

`/usr/bin/activate` is searched and the conda env fails to start.

I ok to create that file, but not on `/usr/bin` => this is the distribution path, I want to use `/usr/local/bin` or `$HOME/.local/bin` for example.

nb_conda_kernels should have a way to configure the activation script.
