### ISSUE TITLE
Older versions of 'conda info --json' do not output "conda_prefix"

### ISSUE THREAD

**Issue by aldanor** [Anaconda-Platform/nb_conda_kernels#119]
These lines fail with older conda installations:

https://github.com/Anaconda-Platform/nb_conda_kernels/blob/db8c10d1eb181ed5b70427e06afe342f1248d2b2/nb_conda_kernels/manager.py#L107

https://github.com/Anaconda-Platform/nb_conda_kernels/blob/db8c10d1eb181ed5b70427e06afe342f1248d2b2/nb_conda_kernels/manager.py#L145

Could it be changed to something like this?

```python
conda_prefix = self._conda_info.get('conda_prefix', self._conda_info.get('root_prefix'))
```

(I've just tried locally and it seems to work with conda 4.1; I'm not sure though where it has to be default_prefix or root_prefix since both seem to be the same in my case. I'm guessing root_prefix)

Here's the (shortened) output of my `conda info --json`:

```json
{
  "channels": [
      "channel1",
      "channel2"
  ],
  "conda_build_version": "1.21.7",
  "conda_env_version": "2.5.2",
  "conda_version": "4.1.12",
  "default_prefix": "/home/miniconda3",
  "envs": [
    "/home/miniconda3/envs/foo",
    "/home/miniconda3/envs/bar",
  ],
  "envs_dirs": [
    "/home/miniconda3/envs"
  ],
  "is_foreign": false,
  "offline": false,
  "pkgs_dirs": [
    "/home/miniconda3/pkgs"
  ],
  "platform": "linux-64",
  "python_version": "3.6.2.final.0",
  "rc_path": "/home/.condarc",
  "requests_version": "2.11.1",
  "root_prefix": "/home/miniconda3",
  "root_writable": true,
  "sys_rc_path": "/home/miniconda3/.condarc",
  "user_rc_path": "/home/.condarc"
}
```

**Comment by mcg1969** [comment]
Can I ask why you're still using conda 4.1? I worry about supporting a version of conda this old. That said, if you were to submit a PR with these changes, and it passes the current tests, I'd be OK with it. We definitely want `root_prefix`, not `default_prefix`.

**Comment by mcg1969** [comment]
I'm going to close this because I really don't want to support versions of conda that are this old—there are some very important improvements in newer versions of conda. That said, as I said above, I'll accept a PR that passes current tests.
