### ISSUE TITLE
Logos not working on Wakari neither win VM

### ISSUE THREAD

**Issue by damianavila** [Anaconda-Platform/nb_conda_kernels#12]
It is not finding the server png...

**Comment by damianavila** [comment]
Ref: https://github.com/ContinuumIO/wakari-issues/issues/251

**Comment by janschulz** [comment]
This might be this: https://github.com/jupyter/notebook/issues/853

**Comment by damianavila** [comment]
Yep, it could be... thanks for the reference @janschulz!

**Comment by damianavila** [comment]
Tested with latest notebook and nb_conda_kernels 2.0.0 and it works as expected. Closing here.
