### ISSUE TITLE
Kernel (environment) list goes off screen, no way to scroll down

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Platform/nb_conda_kernels#121]
I have about 30 conda environments.  With the `nb_conda_kernels` plugin these go below the fold on my screen and I have no way of selecting the ones I cannot see.  The only (unsatisfactory) option is to dramatically reduce the font size until they all show up.  Is there some way this could be fixed?

![image](https://user-images.githubusercontent.com/293525/52003899-caa34180-2493-11e9-94c2-a31cc96b966f.png)

**Comment by mcg1969** [comment]
@ijstokes, it's not clear to me that `nb_conda_kernels` can do anything about this. It doesn't manage any UI elements, it just provides the kernel list to the notebook. I would suggest this is more an issue for the `notebook` repo than anything.

**Comment by mcg1969** [comment]
I'm going to go ahead and close this one because I just can't see a way to fix this within `nb_conda_kernels` itself. That is not to say I don't feel the pain. In fact, JupyterLab's Launcher is worse.
