### ISSUE TITLE
[nb_conda_kernels] couldn't call conda

### ISSUE THREAD

**Issue by nscotto** [Anaconda-Platform/nb_conda_kernels#123]
Hello,

I have installed nb_conda_kernels with `conda install nb_conda_kernels` as mentionned in the installation guide.
It seems that nb_conda_kernels does not find conda as I get the error message `[nb_conda_kernels] couldn't call conda`.
I use jupyterlab with python 3.7 in my base env, I did not install the Anaconda distribution at the default location and I use zshell as my default shell.
I suppose I should mention the conda path somewhere but I don't know where.

**Comment by mcg1969** [comment]
What version of `nb_conda_kernels` are you using? What does `conda list nb_conda_kernels` say?

**Comment by mcg1969** [comment]
I'm going to close this as stale, but please feel free to re-open if you can provide a bit more information for us to reproduce this. In particular, please provide the version of `nb_conda_kernels` and the output of the `conda info` command.
