### ISSUE TITLE
nb_conda_kernels not detecting conda environments

### ISSUE THREAD

**Issue by DayNoone** [Anaconda-Platform/nb_conda_kernels#126]
I am struggeling to get my nb_conda_kernels to detect my conda envs. While jupyter kernelspec only sees my base environment, conda has listed 3. 

```
(base) jupyter kernelspec list
Available kernels:
  python3    C:\ProgramData\Anaconda3\share\jupyter\kernels\python3
```

```
# conda environments:
#
base                  *  C:\ProgramData\Anaconda3
vsb                      C:\ProgramData\Anaconda3\envs\vsb
test_gpu                 C:\Users\DayNoone\.conda\envs\test_gpu

```

However, it looks like nb_conda_kernels finds one of these environments (test_gpu)
![image](https://user-images.githubusercontent.com/2638865/52623437-90cb3580-2eac-11e9-8f99-a8e9ff71e152.png)

**Comment by tdpetrou** [comment]
Looks like this is an issue with conda channel that you have downloaded nb_conda_kernels from. The latest commit was not pushed to conda defaults or conda-forge. It is available on jupycon. 

`conda install jupycon/label/dev::nb_conda_kernels`

Whats happening is that the active environment is not showing up. This is an issue with the manager.py file. Before the last commit it has this line in the `_all_envs` method which was skipping the current environment. 

```
if env_path == sys.prefix:
    continue
```

I would just install from the above channel. As a bad workaround you can start your notebooks from an environment other than the one you would like to actually run.

**Comment by Zsailer** [comment]
This difference between your kernelspec list and your notebook's available kernels is the consequence of nb_conda_kernels' design. 

It **does not** add kernelspecs to your jupyter data files. Rather, it *dynamically* creates kernels from your conda environments when jupyter is launched using a custom `CondaKernelSpecManager` object.

**Comment by mcg1969** [comment]
The screenshot you posted is for the `nb_conda` extension, which is not the same as `nb_conda_kernels`.

**Comment by mcg1969** [comment]
Also, `jupyter kernelspec` cannot make use of `nb_conda_kernels`... yet. See [here](https://github.com/Anaconda-Platform/nb_conda_kernels/pull/104).
