### ISSUE TITLE
Update 2.2.0 -> 2.2.1 fails and leaves system in unusable state

### ISSUE THREAD

**Issue by guillaumedavidphd** [Anaconda-Platform/nb_conda_kernels#130]
Hi,
I updated `nb_conda_kernels` from 2.2.0 to 2.2.1. The update failed with the following error message:
```
Disabling nb_conda_kernels...
Status: disabled
                                                                                                                                                           failed
ERROR conda.core.link:_execute(544): An error occurred while uninstalling package 'conda-forge::nb_conda_kernels-2.2.0-py37_1000'.
UnboundLocalError("local variable 'script_caller' referenced before assignment")
Attempting to roll back.

Rolling back transaction: - DEBUG menuinst_win32:__init__(196): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\ProgramData\Anaconda3', env_name: 'None', mode: 'system', used_mode: 'system'
```
After that, `nb_conda_kernels` stopped working. 
I'm running Windows 10 and conda 4.6.3. Let me know if you need more information.

**Comment by mcg1969** [comment]
Oh no! I'm sorry this happened to you. And yet: there is no variable `script_caller` in `nb_conda_kernels`. There is, however in the [conda source code](https://github.com/conda/conda/search?q=script_caller&unscoped_q=script_caller), leading me to believe this is a bug in `conda`. Indeed, [this PR](https://github.com/conda/conda/pull/8254) seems to be addressing this very issue.

**Comment by mcg1969** [comment]
More here: https://github.com/conda/conda/issues/8285

**Comment by mcg1969** [comment]
I'm going to close this because it's clear that's where the fix is going to come from.
