### ISSUE TITLE
Stripping the kernel name

### ISSUE THREAD

**Issue by wombatonfire** [Anaconda-Platform/nb_conda_kernels#132]
https://github.com/Anaconda-Platform/nb_conda_kernels/blob/e779b519ee8c336520fa943c4556418286b796b4/nb_conda_kernels/manager.py#L181-L182

Is it really necessary to strip the kernel display name here? When working with multiple Python versions in different envs, the display name usually contains the version number, and it becomes harder to choose the right kernel when it is removed.

**Comment by mcg1969** [comment]
We do this primarily for historical reasons. I'm happy to consider a PR to modify this behavior, but my preference would be to make it configurable so that it can be turned on/off by the user.

**Comment by mcg1969** [comment]
Closing as stale/wontfix; but happy to consider a PR under the stated conditions above
