### ISSUE TITLE
Please push 2.2.1 to defaults

### ISSUE THREAD

**Issue by bollard** [Anaconda-Platform/nb_conda_kernels#138]
Hi all,

Would appreciate it if you could push 2.2.1 into the defaults anaconda channel. I'm not seeing my conda environment listed as kernels with the 2.2.0 version I have from `conda install nb_conda_kernels` but this is fixed when I `conda install -c conda-forge nb_conda_kernels` and pick up 2.2.1.

I'm working from an `environment.yml` which only looks at `defaults`, hence the request to get everyone who shares the file up to speed.

Thanks!

**Comment by mcg1969** [comment]
Believe me I would love this too, but this is at the sole discretion of the Anaconda Distribution team—and they don't monitor these issues. I'll ping them but I can't make promises...

**Comment by bollard** [comment]
Thanks Michael. Fingers crossed they take note
