### ISSUE TITLE
Changing the default naming convention

### ISSUE THREAD

**Issue by teoliphant** [Anaconda-Platform/nb_conda_kernels#140]
Currently the name of the environment that shows up is prefixed by "conda : ...".  In situations where this name shows up in a limited horizontal area, the actual name of the package is not visible and the user only sees conda : <one or two characters> and this cannot be used. 

Is the name the environment shows up as configurable?

**Comment by mcg1969** [comment]
The name format is indeed configurable, but the `conda env:` prefix, interestingly, is not. Should be an easy PR.
(Hi Travis!)

**Comment by mcg1969** [comment]
https://github.com/Anaconda-Platform/nb_conda_kernels/blob/master/nb_conda_kernels/manager.py#L62-L74
