### ISSUE TITLE
Broken under Conda 4.7.x (by calling conda.exe info)

### ISSUE THREAD

**Issue by bollard** [Anaconda-Platform/nb_conda_kernels#142]
Hi,

Reposting here as wondering whether this is more appropriate (original [issue](https://github.com/conda/conda/issues/9018) on conda). `nb_conda_kernels` appears to break under Conda 4.7.x when trying to call `conda.exe info`.

Error encountered:

```
C:\Users\user.name>jupyter notebook
[E 09:07:02.430 NotebookApp] [nb_conda_kernels] couldn't call conda:
    Command '['D:\\Miniconda3\\Scripts\\conda.exe', 'info', '--json']' returned non-zero exit status 1.
[I 09:07:02.431 NotebookApp] [nb_conda_kernels] enabled, 0 kernels found
[I 09:07:02.661 NotebookApp] [nb_conda] enabled
```

Call appears to be made [here](https://github.com/Anaconda-Platform/nb_conda_kernels/blob/master/nb_conda_kernels/manager.py#L86:L87)

Thanks

**Comment by bollard** [comment]
I should mention I am running version 2.2.2

**Comment by mcg1969** [comment]
I'm closing this because it's a year old :-( but also we regularly test against newer versions of conda now.
