### ISSUE TITLE
CONDA_ENVS_PATH ignored?

### ISSUE THREAD

**Issue by dfeich** [Anaconda-Platform/nb_conda_kernels#143]
I am experimenting with using CONDA_ENVS_PATH to make various environments visible to our jupyterhub users. In the script for starting up the user's singleuser-server this variable is set and I can confirm it also in the output of a "conda info -a" that I run before the user's jupyter process is started. Also all of the envs from CONDA_ENVS_PATH are visible there. However, in the running jupyter notebook I can only see the envs which belong to the path of the base env and the user's default location at ~/.conda/envs. It seems that CONDA_ENVS_PATH is ignored when searching for available kernels.

I am using nb_conda_kernels  2.2.1.

Thanks

**Comment by mcg1969** [comment]
Sorry for the delay on this one. But `nb_conda_kernels` is not responsible for enumerating the environments—that it delegates, as it should in my view, to conda itself. In particular, if `conda info --envs` cannot see an environment, then `nb_conda_kernels` will not be able too, either.

**Comment by mcg1969** [comment]
So I guess the question is, are you sure that the `CONDA_ENVS_PATH` environment variable is making it to the process that is running `nb_conda_kernels`? My guess is that it is not.
