### ISSUE TITLE
Environment is not getting activated

### ISSUE THREAD

**Issue by tomcatlingcma** [Anaconda-Platform/nb_conda_kernels#144]
## Issue
Conda environments are not being activated before the kernel is started. 

## Explanation

Let's say I am running jupyterlab from within <notebook_environment> and creating a notebook  or console session with a kernel from <my_environment>.

The kernel runs in the correct environment, but 'conda activate <my_environment>' doesn't seem to be applied before the kernel is started.

I suspect this might be a jupyterlab issue rather than a problem with nb_conda_kernels, as running 

`python -m nb_conda_kernels.runner /home/ubuntu/miniconda <my_environment> conda info`

from within <notebook_environment> does behave as I expect. However when I start a notebook or console in jupyterlab with the <my_environment> kernel and run

`os.popen('conda info').read()`

`os.environ`

`System.getenv()` (R)

or similar, I get back info for <notebook_environment> rather than <my_environment>. The kernel is definitely pointing at the right executable because I do see the correct libraries etc.

## Environment

<notebook_environment>
jupyterlab 1.0.4
nb_conda_kernels 2.2.2
conda 4.6 (same behaviour in 4.7)

<my_environment>
R and Python kernels give the same result.

**Comment by tomcatlingcma** [comment]
Duplicate in #145

**Comment by fcollonval** [comment]
Hey @tomcatlingcma, I tested with
jupyterlab 1.1.1 
nb_conda_kernels 2.2.2
conda 4.7.11

If I execute in an environment *test2* notebook `!conda info` or `os.popen('conda info').read()`, I get

```
     active environment : test2
    active env location : /home/fcollonval/miniconda3/envs/test2
            shell level : 3
       user config file : /home/fcollonval/.condarc
 populated config files : /home/fcollonval/.condarc
          conda version : 4.7.11
    conda-build version : 3.18.9
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /home/fcollonval/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/fcollonval/miniconda3/pkgs
                          /home/fcollonval/.conda/pkgs
       envs directories : /home/fcollonval/miniconda3/envs
                          /home/fcollonval/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.7.3 Linux/4.19.0-5-amd64 debian/10 glibc/2.28
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

am I running things differently than you? If not could you try updating jupyterlab and see if it was indeed the source of the error?

**Comment by mcg1969** [comment]
Closing as duplicate
