### ISSUE TITLE
no kernels when envs_dirs contains an empty dir

### ISSUE THREAD

**Issue by Denelvo** [Anaconda-Platform/nb_conda_kernels#148]
This one took a while to figure out, and it is a border condition.

When envs_dirs in .condarc contains an empty directory, conda is fine. But nb_conda_kernels (through jupyter kernelspec list) always returns an empty list. 

This condition happens for example when you're planning on creating a new environment, and you have the dir, but it's not there yet. Because your colleague hasn't provided the spec file yet. 

I don't feel confident enough to write the code, but it should be as simple as adding a test in manager.py. I think.

**Comment by mcg1969** [comment]
I'm unable to reproduce this—I created an empty directory, added it to `envs_dirs`, and it didn't change the kernel listing.

I recognize this is a very old issue, so it's possible it has accidentally been fixed. But note that it is not enough for a directory to exist, or even for a conda environment to exist; it must contain a kernel package, like ipykernel, and its associated `$CONDA_PREFIX/share/jupyter/kernels/*/kernel.json` file.
