### ISSUE TITLE
Build for Python 3.8

### ISSUE THREAD

**Issue by lengau** [Anaconda-Platform/nb_conda_kernels#154]
We're looking to move our dev environment to 3.8, but currently this is our blocker

It looks like there's a Python 3.8 build on conda-forge that seems to work just fine on a manual install. Can I make a PR that enables the build for 3.8 or do you have blockers? (I couldn't find anything)

**Comment by mcg1969** [comment]
Sorry for the delay—I'll work this into the PR I'm currently working on

**Comment by mcg1969** [comment]
Keep in mind, however, that the _right_ thing to do is built a noarch package and then _test_ it on a matrix of Pythons.

**Comment by mcg1969** [comment]
We're doing this now in current CI. Can't speak for conda-forge but I'm reasonably sure they are as well.
