### ISSUE TITLE
conda update -n env_name nb_conda_kernels - was not updating to version 2.2.4 in Ubuntu 20.04

### ISSUE THREAD

**Issue by rohan-paul** [Anaconda-Platform/nb_conda_kernels#171]
Was not being able to update to version 2.2.4 (from current version of 2.2.3) with the below command. Not sure if I am missing something basic here.

`conda update -n env_name nb_conda_kernels`

**I also ran below**

```
conda update -n env_name --all
```

**And the below command too**

`conda update -n env_name nb_conda_kernels --no-pin`

**But still was not updating to v 2.2.4**

And in Terminal got below a very long list that was to be updated - and there's in that `nb_conda_kernels` was not there.

**Other possibly useful information**

![image](https://user-images.githubusercontent.com/12703975/90159380-efc57f80-ddad-11ea-80b7-8014f80121ee.png)

**Comment by mcg1969** [comment]
What happens if you do `conda install nb_conda_kernels=2.2.4`? Please share the entire output.

**Comment by mcg1969** [comment]
closing as stale (and because it is actually a conda issue, not an nb_conda_kernels issue, without further evidence to the contrary)
