### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by fcollonval** [Anaconda-Platform/nb_conda_kernels#178]
Hey @mcg1969 

I have deployed internally and use successfully #172 for 10 days. So I was wondering if you could do a release including it?

> Note: regarding your previous attempt to switch to noarch and #177, a solution to set the default kernelspec manager maybe [Automatic installation](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Distributing%20Jupyter%20Extensions%20as%20Python%20Packages.html#Automatically-enabling-a-server-extension-and-nbextension)
 > I did not try it for other option than the activation of a server extension - so I am not sure it will be usable here.

**Comment by mcg1969** [comment]
Agreed, will get this done

**Comment by fcollonval** [comment]
Thanks @mcg1969

**Comment by mcg1969** [comment]
2.3.0 is tagged
