### ISSUE TITLE
Disable or remove nb_conda_kernels

### ISSUE THREAD

**Issue by jamesbaye** [Anaconda-Platform/nb_conda_kernels#189]
I can't find how to temporarily disable, or permanently remove, nb_conda_kernels.

I tried to permanently remove with conda (`conda remove nb_conda_kernels`), but that flags environment inconsistencies similar to #188 before hanging.

**Comment by ZorrowHu** [comment]
https://github.com/conda/conda/issues/8490#issuecomment-614501058
You should really try this! I've fixed it and ran perfectly.

**Comment by lijiayan2020** [comment]
`pip uninstall nb_conda `

**Comment by mcg1969** [comment]
I'm going to close as stale here, but I'm not averse to this being re-opened if necessary
