### ISSUE TITLE
kernel_spec_manager_class not recognized by ListKernelSpecs

### ISSUE THREAD

**Issue by lwjyel** [Anaconda-Platform/nb_conda_kernels#193]
Before `conda install nb_conda_kernels` in 'base' env,
`jupyter kernelspec list` outputs as normal,

**Available kernels:
   python3    User/.../kernels/python3**

After `conda install nb_conda_kernels` in 'base' env,
`jupyter kernelspec list` outputs with a WARNING,

**[ListKernelSpecs] WARNING | Config option `kernel_spec_manager_class` not recognized by `ListKernelSpecs`.
Available kernels:
  python3    /Users/.../kernels/python3**

Also replicated in another environment (created by duplicating 'base' env before installation of `nb_conda_kernels`).

**Comment by fcollonval** [comment]
Don't worry about that. This comes from the current lack of generic dynamic loading mechanism for custom kernel spec provider.

**Comment by lwjyel** [comment]
Cool, thanks.

**Comment by scruel** [comment]
@fcollonval When this warning can be fixed to remove? Still have such warning while executing the same command, and more when installing packages:
```
 Config option `kernel_spec_manager_class` not recognized by `EnableNBExtensionApp`.
Enabling notebook extension nb_conda/main...
      - Validating: OK
Enabling tree extension nb_conda/tree...
      - Validating: OK
Config option `kernel_spec_manager_class` not recognized by `EnableServerExtensionApp`.
```
