### ISSUE TITLE
Can you please also provide a pip package for this?

### ISSUE THREAD

**Issue by PhilipMay** [Anaconda-Platform/nb_conda_kernels#204]
Hi,
I do like conda, jupyter and nb_conda_kernels but I prefer to
use conda as an env. manager and pip as my package installer.

Could you please provide a pip package at pypi?

Thanks
Philip

**Comment by PhilipMay** [comment]
Hello dear maintainers of this project.
What about this idea? What do you think?

Thanks
Philip

**Comment by fcollonval** [comment]
I don't think it will ever happen as this will result in potential non-working installation as it is impossible to tell pip that this package needs conda. So users may end up installing it from pip without understanding why it is not working.

**Comment by zhang-dut** [comment]
> Hi, I do like conda, jupyter and nb_conda_kernels but I prefer to use conda as an env. manager and pip as my package installer.
> 
> Could you please provide a pip package at pypi?
> 
> Thanks Philip

Bro, You can download it from **https://pypi.org/** and enter the keyword **nb_conda_kernels(or nb_conda)** in the search box

**Comment by mcg1969** [comment]
I personally don't support this option. This package is too closely dependent upon conda.
