### ISSUE TITLE
Conda Kernels for R not being created

### ISSUE THREAD

**Issue by mrduane** [Anaconda-Platform/nb_conda_kernels#21]
I'm seeing problems creating R kernels. Here's what I've done:
- Conda installed the nb\* extensions
- Created  Python2 & Python3 envs in the Conda tab in Jupyter. They show up as kernels
- Tried creating an R env. Didn't work b/c I didn't have the R channel in my .condarc
- Fixed .condarc and tried again. The Conda env is created, but not the kernel.
- Added a few more Python2, Python3 & R envs; I'm only seeing Python kernels available

**Comment by ijstokes** [comment]
@mrduane a few comments ( @damianavila can correct me if I'm wrong)

I assume this is for an AEN deployment.  If so, it would help to know which version.

1. The `r` channel should automatically be included.  If it isn't then a step was missed in the upgrade process or (maybe more likely) there is a conflicting `.condarc` file (see https://github.com/conda/conda/issues/654)

2. R kernels are not automatically installed.  Adding the R channel to `condarc` doesn't mean you're automatically going to get all the packages in that channel.  For that, you need to modify the `- defaults` section where you can specify a base set of packages that should go into every new environment.  In AEN the default is **not** to include R, but see the notes here: http://docs.wakari.io/we/install/deploy/installation_update.html#server -- you can add `r-essentials` to your `.condarc`, but (see issue 654 I referenced above) `.condarc` files can mess things up if there isn't "just one", and on top of that it needs to be set on the right AEN sub-component (in this case, the Compute Launcher node) -- see docs here: http://docs.wakari.io/we/install/deploy/installation_update.html#compute

3. So finally, if you want R kernels to appear you'll need to do what it says in Step 8 of that last link, namely:

    ```
    conda install -c r r-essentials
    ```
    or if it is for a new conda environment then:
    ```
    conda create -c r -n my_new_env r-essentials foo_pkg bar_pkg
    ```

Do any of those comments help resolve your problem?

But the fact that we have to explain that to you makes me think we need to do something differently here.  Some suggestions:

1. Install R kernels by default for everyone in AEN.  If you don't want them then you (or your admin) can remove them on a case-by-case (per-environment) basis or from the `.condarc` file.

2. Improve documentation.  But people don't read or don't remember docs, so I don't know if this is worth it.

Thoughts?

**Comment by ijstokes** [comment]
@mrduane creating the conda env like this worked:

```
conda create -n testaen -c anaconda-nb-extensions -c r -c wakari nb_conda nb_conda_kernels r-essentials
```

I am then able to start Jupyter Notebook, create a new notebook with R kernels, or open existing notebooks that use R.

However:

i) there are other problems that I will report separately; and
ii) I created the env from the CLI, not from the conda tab.

**Comment by mrduane** [comment]
@ijstokes @damianavila FYI, this is also unreliable for me in our AE-N demo env, but it does seem to be working well in the Trial VM.

**Comment by damianavila** [comment]
As @ijstokes mentioned before, in every situation you want to have R functionality, you need to have the r-kernel installed in the environment you are creating... so in the step you are creating the environment, request to additionally install `r-essentials` or specifically the `r-irkernel` and you will have the R options available...
In the case of the trialVM and the AEN, we provide `r-essentails` (and some other things) by default, this is why is probably working OK... BUT, if you use customized deafult environments in AEN, you have to be aware to install all the needed dependencies to be able to have the R executable there and the option available in the notebook.
Ans yes @ijstokes, I think we need more documentation about this on AEN, and some docs here at nb_conda_kernels...

**Comment by ijstokes** [comment]
@mrduane and @trentoliphant it sounds like we may be discussing the same issue in two separate issues.  See the reference above to #311 in the wakari-issues repo.

**Comment by mrduane** [comment]
@ijstokes thanks, looking at the other issue now. @damianavila I do have `r-irkernel` installed.

**Comment by damianavila** [comment]
> @mrduane and @trentoliphant it sounds like we may be discussing the same issue in two separate issues. See the reference above to #311 in the wakari-issues repo.

It could be...

**Comment by damianavila** [comment]
Solved upstream. Closing.
