### ISSUE TITLE
Lowercase Paths during Lookup

### ISSUE THREAD

**Issue by hakasapl** [Anaconda-Platform/nb_conda_kernels#218]
Hi All,

I came across an issue where any conda environments with uppercase characters were not able to start a kernel in Jupyter. Eventually I found out that it is due to nb_conda_kernels is making the path lowercase.
In manager.py, line 218:
```
kernel_dir = dirname(spec_path).lower()
```
When I manually remove the .lower() portion - things start working as expected. Because I am on a case-sensitive OS as part of a HPC cluster (Ubuntu Linux), I was confused to find this.

Is nb_conda_kernels intended to be only used on Windows or other case-insensitive systems? Either way, even in a case-insensitive OS, mismatched uppercase/lowercase chars shouldn't stop the application from working. Is this something that should be removed? Happy to submit a PR if so, but it feels like I'm missing something so I'll wait for now.

**Comment by danykaufman** [comment]
Same here.
Removing the .lower() portion fixes linux functionality when path contains uppercase letters.
