### ISSUE TITLE
Work with Mamba?

### ISSUE THREAD

**Issue by AniAggarwal** [Anaconda-Platform/nb_conda_kernels#250]
Is there a way to make this package work with mamba (specifically micromamba) instead of conda?
I get the following error and my envs don't show up unless manually installed.
```log
[E 2024-03-04 11:20:04.378 ServerApp] [nb_conda_kernels] couldn't call conda:
    [Errno 2] No such file or directory: 'conda'
```

**Comment by mcg1969** [comment]
This is a duplicate of #234; so I'm going to close it, but not for negative reasons.

**Comment by AniAggarwal** [comment]
No idea how I didn't find that issue before making this one. Thanks for taking a look.

**Comment by mcg1969** [comment]
No worries at all.
