### ISSUE TITLE
Error while updating to 1.0.3

### ISSUE THREAD

**Issue by michaelaye** [Anaconda-Platform/nb_conda_kernels#30]
My system:
OSX 10.10.5, this is a conda Python 3.5 environment. only default channel in config, nb_conda_kernel was manually added via the conda-forge channel with the command:

``` bash
conda install -c conda-forge nb_conda_kernels
```

**Comment by michaelaye** [comment]
I see though, that now this package comes from the default channel, that's nice!

**Comment by damianavila** [comment]
I could not verify this issue. Closing now, reopen it if you see it again.
