### ISSUE TITLE
After recent update, no envs are found.

### ISSUE THREAD

**Issue by michaelaye** [Anaconda-Platform/nb_conda_kernels#36]
After the recent update to 1.0.3, none of my conda envs are being found, for some reason only Python 2 and 3 are there, but the Python 3 is the conda default 3.4, while I usually work in Python 3.5.

It was totally working before, so this is a regression on my side.

System: OSX 10.10.5, miniconda 3.4, several Python 3 envs and one Python 2.

**Comment by bollwyvl** [comment]
@michaelaye  We've released versions of `nb_conda`, `nb_conda_kernels` and `nb_anacondacloud` through the official Anaconda conda repos that should resolve the issues you are seeing!

```shell
conda update nb_conda nb_conda_kernels nb_anacondacloud
```

As-installed kernel names that are eligible for being `default` (e.g. `python2`, `python3`, `ir`, etc.) will be maintained unmodified, so they should always appear there.

The downside is as many as three options for the current env, i.e. if you are in root, you will see _Python 2_ and _Python [root]_ and _Python [default]_, you can now reproducibly capture which environment your kernel should run against.

meta: https://github.com/Anaconda-Platform/anaconda-nb-extensions/issues/166
