### ISSUE TITLE
Consider only registering R kernels if IRkernel is installed

### ISSUE THREAD

**Issue by cel4** [Anaconda-Platform/nb_conda_kernels#37]
The current version registers R kernels in the notebook interface if R is available. Apparently it does not check if the IRkernel is actually installed.

Since environments without IRkernel will not work anyway, I would prefer not to see them in the interface.

**Comment by janschulz** [comment]
JFYI, this is implemented in https://github.com/Cadair/jupyter_environment_kernels

**Comment by damianavila** [comment]
We are detecting R and jupyter... in fact we should be further the road and test for `IRkernels` and `ipykernel`. If jupyter is installed, ipykernels is installed... but R can be installed without the existence of the ir-kernels.

**Comment by janschulz** [comment]
I install ipykernels independent, of jupyter...

**Comment by damianavila** [comment]
>I install ipykernels independent, of jupyter...

Yep... that's why I said we need to be more specific here...

**Comment by janschulz** [comment]
Oups, I misinterpreted that line as saying that checking for jupyter is enough:

>  If jupyter is installed, ipykernels is installed... but R can be installed without the existence of the ir-kernels.

**Comment by damianavila** [comment]
> Oups, I misinterpreted that line as saying that checking for jupyter is enough:

No problem :wink: sorry to not be clear enough.

**Comment by mcg1969** [comment]
I'm addressing this in #80

**Comment by mcg1969** [comment]
Fixed in #80
