### ISSUE TITLE
Does not update the default kernel

### ISSUE THREAD

**Issue by to266** [Anaconda-Platform/nb_conda_kernels#38]
After [poping](https://github.com/Anaconda-Platform/nb_conda_kernels/blob/master/nb_conda_kernels/manager.py#L122) the existing kernels, does not replace the [default kernel name](https://github.com/jupyter/notebook/blob/master/notebook/services/kernelspecs/handlers.py#L54) in the `kernel_manager`.

As a result, this  https://github.com/jupyter/jupyterlab/issues/417

**Comment by bollwyvl** [comment]
@to266  We've released versions of `nb_conda`, `nb_conda_kernels` and `nb_anacondacloud` through the official Anaconda conda repos that should resolve the issues you are seeing! 

```shell
conda update nb_conda nb_conda_kernels nb_anacondacloud
```

As-installed kernel names that are eligible for being `default` (e.g. `python2`, `python3`, `ir`, etc.) will be maintained unmodified, so they should always appear there.

The downside is as many as three options for the current env, i.e. if you are in root, you will see _Python 2_ and _Python [root]_ and _Python [default]_, you can now reproducibly capture which environment your kernel should run against.

meta: https://github.com/Anaconda-Platform/anaconda-nb-extensions/issues/166
