### ISSUE TITLE
"Kernel not found" doesn't list all possible kernels

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Platform/nb_conda_kernels#46]
I am opening a new notebook and the kernel is not found.  I get this dialog box:

![screen shot 2016-09-13 at 10 32 13 am](https://cloud.githubusercontent.com/assets/293525/18478032/cad8c880-799d-11e6-9113-c0ffa8a5a6c7.png)

The problem is that list is not complete.  It is missing two kernel options, "R [default]" and "SAS", which I **can** see at a later point (if I select "Continue without kernel"):

![screen shot 2016-09-13 at 10 32 30 am](https://cloud.githubusercontent.com/assets/293525/18478064/e9edb276-799d-11e6-818c-a75113776ae7.png)

This is inside AEN.  Relevant package versions:

```
$ conda list | grep -i -e nb_ -e notebook -e jupyter                                                                
_nb_ext_conf              0.2.0                    py35_0    defaults                                                                                         
jupyter                   1.0.0                    py35_3    defaults                                                                                         
jupyter-client            4.3.0                     <pip>                                                                                                     
jupyter-console           4.1.1                     <pip>                                                                                                     
jupyter-core              4.1.0                     <pip>                                                                                                     
jupyter_client            4.3.0                    py35_0    defaults                                                                                         
jupyter_console           4.1.1                    py35_0    defaults                                                                                         
jupyter_core              4.1.0                    py35_0    defaults                                                                                         
nb_anacondacloud          1.1.0                    py35_0    defaults                                                                                         
nb_conda                  1.1.0                    py35_0    defaults                                                                                         
nb_conda_kernels          1.0.3                    py35_0    defaults                                                                                         
notebook                  4.2.1                    py35_0    defaults
```

~~If any of those are out of date, please advise the safe way to update them.~~

I **know** some of these are out of date, but I do not know how or where to safely update them.

**Comment by damianavila** [comment]
>The problem is that list is not complete.

I think it is complete... that notebook was saved with a python kernel and when it can not find a Python3 kernel name, it shows you all the "python" kernels available, not the R or the SAS... this is a behavior from upstream trying to match compatible kernels...

**Comment by ijstokes** [comment]
OK, good to know, and that behavior makes sense.  In my case, I was switching between language kernels inside the notebook.
