### ISSUE TITLE
Upstream is validating names, we should be compliant to that...

### ISSUE THREAD

**Issue by damianavila** [Anaconda-Platform/nb_conda_kernels#51]
Ref: https://github.com/jupyter/jupyter_client/pull/221

Thanks @blink1073 for the reference.

**Comment by blink1073** [comment]
I am able to make a conda env with a space in its name, FWIW.

**Comment by damianavila** [comment]
>I am able to make a conda env with a space in its name, FWIW.

Thanks!

**Comment by mcg1969** [comment]
#91 ensures that the "short" environment names validate, even with Unicode characters and spaces.
