### ISSUE TITLE
How to create a new conda env based kernel programmatically?

### ISSUE THREAD

**Issue by jhprinz** [Anaconda-Platform/nb_conda_kernels#52]
This is a related question to #45 and basically asking for help with the internals as I was not able to find enough information in the documentation.

I need to create a kernel programmatically and currently do this with code looking similar to:

```py
from jupyter_client.manager import KernelManager
km = KernelManager()
kernel = km.start_kernel(...)
```

and I assume it uses my one kernel that is listed using either

```py
import ipykernel.kernelspec
ipykernel.kernelspec.get_kernel_dict()

{'argv': ['~/anaconda/bin/python',
  '-m',
  'ipykernel',
  '-f',
  '{connection_file}'],
 'display_name': 'Python 2',
 'language': 'python'}
```

or

```py
import jupyter_client.manager as ma
ma.kernelspec.find_kernel_specs()

{'python2': '~/anaconda/lib/python2.7/site-packages/ipykernel/resources'}
```

I installed initially conda with Python2, but added Python3 environments as well.

Now: _How can I access the conda environment kernels?_ Especially get the list and finally create a kernel using the KernelManager in the environment of my choice like jupyter is doing. I was not able to find something in the documentation.

I had written a little tool to run notebooks as tests and compare the output, etc. so that it looks like a nosetest. To test a notebook automatically in multiple environments / python versions would be great.

**Comment by damianavila** [comment]
Something along these lines should give you the info you need:

```python
from nb_conda_kernels import CondaKernelSpecManager

cksm = CondaKernelSpecManager()

all_envs = cksm._all_envs()
```

I think...

**Comment by jhprinz** [comment]
@damianavila Hi, this works. Now I still need to figure out how to create the appropriate kernel, but that should be doable... Unless you spontaneously know this. I would close this. Thanks!

**Comment by damianavila** [comment]
>  Now I still need to figure out how to create the appropriate kernel, but that should be doable... Unless you spontaneously know this

Look into the manager.py source, it should contain all you need (if not, check the parent class KernelSpecManager as well, because maybe have the pieces you need). Let us know if you need help.

Cheers.

**Comment by damianavila** [comment]
Btw, check this function: https://github.com/Anaconda-Platform/nb_conda_kernels/blob/master/nb_conda_kernels/manager.py#L180, it will give you an idea about how to create the proper kernelspecs...

**Comment by damianavila** [comment]
I think the main questions are answered. Closing here.
