### ISSUE TITLE
Extension not loading

### ISSUE THREAD

**Issue by battmatt** [Anaconda-Platform/nb_conda_kernels#53]
I am working to set up a jupyter server running on a mac pro using the latest anaconda distribution.  nb_conda_kernals will not load:

![screen shot 2016-12-01 at 3 52 28 pm](https://cloud.githubusercontent.com/assets/1753879/20817763/674b84c2-b7de-11e6-8294-488f7fb0ca25.png)

I am able to import the package from within a jupyter notebook.  Let me know what other information might be helpful.

**Comment by damianavila** [comment]
You have the extensions installed at sys-prefix and also the user space... that could be certainly problematic. Can you try to backup things at `/Users/bfx/.jupyter` and remove that folder and then try to install nb_conda_kernels in the anaconda root environment and report back? Thanks!

**Comment by battmatt** [comment]
So a bit of background.  I am trying to avoid using anaconda as my system python.  I wanted to use it to get a notebook server up and running.  This is why I installed at /usr/local/var/anaconda3.  I am also add the anaconda folder to the end of my PATH variable rather than the beginning.

Here is what I just tried:

`mv /Users/bfx/.jupyter /Users/bfx/.jupyterbk
cd /usr/local/var/anaconda3
source activate root
jupyter serverextension enable nb_conda_kernels
`

And I am getting the same error message as before.


I then tried
`
conda update nb_conda nb_conda_kernels nb_anacondacloud
`

And it says all of the packages are installed. And if I run the notebook server, I am able to import nb_conda_kernels.  The python executable is /usr/local/var/anaconda3/bin/python.

I'm assuming this is also just me trying to be too fancy with things I don't fully understand.  Thanks for your help.

**Comment by damianavila** [comment]
> jupyter serverextension enable nb_conda_kernels

That could be the isssue, nb_conda_kernels is not a serverextension... is another KernelSpecManager... to enable it you need to:
```
/usr/local/var/anaconda3/bin/python -m nb_conda_kernels.install --enable --prefix=/usr/local/var/anaconda3
```
In any case the conda package post-script step should do that... I am not sure why is not doing it in your case...

If you look into the `/usr/local/var/anaconda3/etc/jupyter/jupyter_notebook_config.json` you need to see the alternative CondaKernelSpecManager:

```
{
  "NotebookApp": {
    "nbserver_extensions": {
      "nb_anacondacloud": true,
      "jupyterlab": true,
      "nb_conda": true,
      "nbpresent": true
    },
    "kernel_spec_manager_class": "nb_conda_kernels.CondaKernelSpecManager"
  }
}
```

**Comment by battmatt** [comment]
The last piece of information which I left out, that seems to be the missing piece.  Is that I am running this with my own config file.

When I do this, nb_conda_kernels works:

`
/usr/local/var/anaconda3/bin/jupyter notebook
`
And with this it does not:

`
/usr/local/var/anaconda3/bin/jupyter notebook --config=~/.jupyter/jupyter_notebook_config.py 
`

The fields that I updated in the config are:

> c.NotebookApp.certfile = '/Users/bfx/.jupyter/myjupytercert.pem'

> c.NotebookApp.ip = '*'

> c.NotebookApp.keyfile = '/Users/bfx/.jupyter/myjupyterkey.key'

> c.NotebookApp.notebook_dir = '/usr/local/var/jupyter'

> c.NotebookApp.open_browser = False

> c.NotebookApp.password = 'a password sha'

> c.NotebookApp.port = 8888

**Comment by battmatt** [comment]
I just updated ~/.jupyter/jupyter_notebook_config.py

to include

"kernel_spec_manager_class": "nb_conda_kernels.CondaKernelSpecManager"


and it seems to be working now.

**Comment by damianavila** [comment]
>and it seems to be working now.

I was going to suggest that... nice it is solved!

Closing this one but feel free to reopen if you still see the issue.
