### ISSUE TITLE
Need source activate done before notebook based on kernel/conda env launched

### ISSUE THREAD

**Issue by davidslac** [Anaconda-Platform/nb_conda_kernels#54]
My colleagues are standing up a jupyterhub to allow users to select conda environments I maintain. They setup a environment to run jupyterhub out of a python 3 conda environment, and then users select a python 2.7 conda environment. The issue is that once the kernel has started, the environment has issues. In particular the PATH still points to the python 3 environment jupyterhub runs from. 

The conda environements I maintain set environment variables using the
 ```
etc/conda/activate.d/env_vars.sh 
```
mechanism. It does not appear that the jupyterhub ipython mechanism has done anything like a source activate for the environment for the kernel. How does this work?

**Comment by damianavila** [comment]
> It does not appear that the jupyterhub ipython mechanism has done anything like a source activate for the environment for the kernel. How does this work?

That's correct, `nb_conda_kernels` is creathing a kernespec on the fly pointing to the environment where jupyter (ipykernel) is detected.

I think you are experiencing something like this: https://github.com/Anaconda-Platform/nb_conda_kernels/issues/19

**Comment by janschulz** [comment]
@davidslac if you really need activate support, you might like to look at  https://github.com/Cadair/jupyter_environment_kernels/pull/29.

**Comment by mcg1969** [comment]
I'm working on this in #80

**Comment by mcg1969** [comment]
Fixed in #80
