### ISSUE TITLE
Python 3.6 package

### ISSUE THREAD

**Issue by jzuhone** [Anaconda-Platform/nb_conda_kernels#61]
Is there a plan to make a conda package for Python 3.6?

**Comment by haobibo** [comment]
Besides, this package now depends on a lower version of `conda`.

**Comment by damianavila** [comment]
Yep, plans are to build these packages in the next few weeks.

**Comment by basnijholt** [comment]
There is a Python 3.6 package on the [conda-forge](https://anaconda.org/conda-forge/nb_conda_kernels/files) channel 😄

**Comment by damianavila** [comment]
>There is a Python 3.6 package on the conda-forge channel :smile:

That's correct, tested and working as expected. Closing this one now.

**Comment by damianavila** [comment]
I have release 2.1.0 some days ago in conda-forge inlcuding py36 support.
Btw, conda packages from `defaults` channel will be available soon.
