### ISSUE TITLE
nb_conda_kernels doesn't uninstall properly and breaks the notebook

### ISSUE THREAD

**Issue by dhirschfeld** [Anaconda-Platform/nb_conda_kernels#63]
After `conda uninstall nb_conda_kernels` my notebook no longer works. I get the below error message when I try to start the notebook:
```
The 'kernel_spec_manager_class' trait of <notebook.notebookapp.NotebookApp object at 0x00000168B468AC18> instance must be a type, but 'nb_conda_kernels.CondaKernelSpecManager' could not be imported
```

Any idea where I can find that configuration value to delete it?

**Comment by dhirschfeld** [comment]
Running `jupyter --paths` I was able to find the config in the `etc` dir and delete it

**Comment by BrenBarn** [comment]
Is this issue actually fixed?  It seems like a real fix would mean uninstall nb_conda_kernels removes that file itself.

**Comment by damianavila** [comment]
> Is this issue actually fixed? It seems like a real fix would mean uninstall nb_conda_kernels removes that file itself.

This https://github.com/conda-forge/nb_conda_kernels-feedstock/blob/master/recipe/pre-unlink.sh should take care to remove that piece at uninstalling time.

**Comment by nocibambi** [comment]
> Running `jupyter --paths` I was able to find the config in the `etc` dir and delete it

Sorry for the resurrection. I have the same issue. I have nothing in /etc. Maybe you remember what did you delete specifically? :)

**Comment by OrangeCat-AMi** [comment]
> 这个问题真的解决了吗？看来，真正的修复意味着要`uninstall nb_conda_kernels`删除该文件本身。

run the order，maybe occur uninstall pycharm, sure?
