### ISSUE TITLE
How to specify env_filter?

### ISSUE THREAD

**Issue by pankajkumar229** [Anaconda-Platform/nb_conda_kernels#65]
How do we specify it in jupyter_notebook_config or on the command line?

**Comment by damianavila** [comment]
See this issue: https://github.com/Anaconda-Platform/nb_conda_kernels/issues/49

**Comment by pankajkumar229** [comment]
I get the following error "notebook stderr: [W 06:13:32.371 NotebookApp] Config option `env_filter` not recognized by `CondaKernelSpecManager`." when I launch jupyter notebook --CondaKernelSpecManager.env_filter="xyz"

**Comment by pankajkumar229** [comment]
nb_conda_kernels version is 2.0.0.

**Comment by pankajkumar229** [comment]
I tried 
c.CondaKernelSpecManager.env_filter = "pyvertest" 
but that did not work

**Comment by damianavila** [comment]
That's probably because the functionality is in master but not released yet.
You need to use it from master until we build new packages from the latest master (probably next week).

**Comment by pankajkumar229** [comment]
Thanks! I will wait for the next release.

**Comment by damianavila** [comment]
Closing in favor of #49

**Comment by pankajkumar229** [comment]
How do I get the latest release? When I get nb_conda_kernels from conda_forge I still get the same error.

**Comment by damianavila** [comment]
@pankajkumar229, no I just close this one because it is already duplicated in #49.

**Comment by damianavila** [comment]
@pankajkumar229 you can download the latest release from conda-forge, still missing docs but in #49 you have some hints about how to use it. Let me know if you need more helps. Cheers.

**Comment by damianavila** [comment]
Btw, conda packages from `defaults` channel will be available soon.
