### ISSUE TITLE
Potential unbound local error in manager.py

### ISSUE THREAD

**Issue by sccolbert** [Anaconda-Platform/nb_conda_kernels#66]
https://github.com/Anaconda-Platform/nb_conda_kernels/blob/master/nb_conda_kernels/manager.py#L188-L211

If `info['language_key']` is ever anything other than `'py'` or `'r'`, line 210 will fail with an unbound local error. Currently, that condition won't occur because only `'py'` and `'r'` kernels are loaded. But if the discovery code is ever extended to support another language, this code might be missed. Maybe better to add an explicit `else` clause which either throws, or creates an empty kspec.

**Comment by damianavila** [comment]
Good catch! You are totally right. Thanks for the report!

**Comment by mcg1969** [comment]
#80 takes kernelspecs in directly, and modifying them, instead of constructing them from scratch. So I believe we've adequately addressed this issue.
