### ISSUE TITLE
R-kernel not working on win

### ISSUE THREAD

**Issue by damianavila** [Anaconda-Platform/nb_conda_kernels#7]
https://github.com/Anaconda-Server/nb_conda_kernels/pull/6#issuecomment-173984108

**Comment by bollwyvl** [comment]
Here's the issue i am getting:

<img width="1440" alt="screen shot 2016-01-22 at 3 56 20 pm" src="https://cloud.githubusercontent.com/assets/45380/12522809/ba60f6c0-c120-11e5-96a8-289ef9c5b12e.png">

Steps to reproduce:
```bash
conda create -n rsupport python=3.5
activate rsupport
conda install -c r r-essentials notebook
# install this sutff, either through `python setup.py develop` or `conda build/install`
jupyter notebook
# try to start a new notebook with any r kernel
```

**Comment by mcg1969** [comment]
Likely stale. I just tested R kernels in master, on Windows and Unix.
