### ISSUE TITLE
Rename Kernels with Custom Names?

### ISSUE THREAD

**Issue by rbhatia5** [Anaconda-Platform/nb_conda_kernels#71]
It would be great if we could rename the kernels made available by this plugin. If you use jupyterlab with this extension enabled, it's almost impossible to quickly read which environment's kernel you're choosing.

**Comment by damianavila** [comment]
Changing names would add a lot of complexity to the extension, maybe we do better at the time to show the available kernels in the jupyterlab context?

**Comment by mcg1969** [comment]
I'm going to close this, but I would be happy to review a solid PR to do this, as long as it is configurable. In fact, I believe #87 is an attempt to roughly do this.
