### ISSUE TITLE
Trying to set default kernel

### ISSUE THREAD

**Issue by michaelaye** [Anaconda-Platform/nb_conda_kernels#72]
I found this potential candidate in the jupyter config file, to set a default kernel, but that's possibly not being read by nb_conda_kernels? :

c.MultiKernelManager.default_kernel_name = 'conda env:stable'

If not this, how could I set a default kernel using `nb_conda_kernels`?

**Comment by mcg1969** [comment]
@michaelaye, from what I'm seeing on [https://jupyter-notebook.readthedocs.io/en/stable/config.html](this page), this configuration settings applies to `MultiKernelManager`. This module doesn't change that class, and I'm not seeing any reason why our code would break `MultiKernelManager` in this way. Can you offer some information to reproduce this?

**Comment by mcg1969** [comment]
@michaelaye I've been thinking more about this, and I think you have to use the _short_ kernel name; `'conda env:stable'` is the long/display name. Try `conda-env-stable-py` and see if that does it.

**Comment by mcg1969** [comment]
https://github.com/jupyter/notebook/issues/3338

> The 'default' kernel isn't currently used much. When you open a notebook, it open with the kernel recorded in its metadata.

I tried to set the default kernel name too, and to be frank, I couldn't even figure out how to take advantage of it within Jupyter. Creating a new notebook forces me to select a kernel, changing the kernel forces me to select one; there seems to be no way within `notebook` to go with the default.

**Comment by mcg1969** [comment]
Feel free to re-open if you can show how to make this useful. But note, as I said above, you need to use the _short_ kernel name in the config. Try `python -m nb_conda_kernels list` to see the full list of detected kernels and their names.

**Comment by michaelaye** [comment]
That's a nice command.
One question though:
Why is the currently active conda env found twice, both as full name and with the 'python3' identifier?

```bash
$ python -m nb_conda_kernels list                                                            (py37)
[ListKernelSpecs] [nb_conda_kernels] enabled, 3 kernels found
Available kernels:
  conda-env-py37-py              /users/klay6683/miniconda3/envs/py37/share/jupyter/kernels/python3
  conda-env-pyviz-tutorial-py    /users/klay6683/miniconda3/envs/pyviz-tutorial/share/jupyter/kernels/python3
  conda-env-test-py              /users/klay6683/miniconda3/envs/test/share/jupyter/kernels/python3
  python3                        /Users/klay6683/miniconda3/envs/py37/share/jupyter/kernels/python3
```

**Comment by mcg1969** [comment]
Ha! Because when I eliminated the redundancy people complained, and made a good case. I can't delete the "python3" entry because that comes from the superclass. But the longer-named version has the advantage of consistency---no matter which notebook environment you see it from, it will always have that name.

**Comment by mcg1969** [comment]
Incidentally, that command just calls a monkeypatched version of `jupyter kernelspec list`.

**Comment by lovellbrian** [comment]
I want to connect to the local runtime in a conda environment via Jupyter notebooks.  The conda environment has tensorflow and the GPU libraries.  I can make a new kernel in my Jupyter notebook server that uses this environment but Google Colab will only connect to the Python3 Jupyter kernel. How do I change the default Jupyter notebook kernel or how do I tell Colab which kernel to connect to?  I tried MultiKernelManager.default_kernel_name = 'tfgpu' but it doesn't work.

**Comment by dcguim** [comment]
[+1] It would be really nice if it was possible to specify a custom kernel specification as an argument in the `jupyter notebook` command.
```
 ~/work/ml/tensorflow: jupyter notebook **--MultiKernelManager.default_kernel_name='tensorflow'**
[I 13:36:37.249 NotebookApp] Serving notebooks from local directory: /Users/dguim/work/ml/tensorflow
[I 13:36:37.249 NotebookApp] Jupyter Notebook 6.3.0 is running at:
[I 13:36:37.249 NotebookApp] http://localhost:8888/?token=fbe31b3aa194bcd7047fbed2c3622b61b2eff8ac69caf495
[I 13:36:37.249 NotebookApp]  or http://127.0.0.1:8888/?token=fbe31b3aa194bcd7047fbed2c3622b61b2eff8ac69caf495
[I 13:36:37.249 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 13:36:37.251 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/dguim/Library/Jupyter/runtime/nbserver-3272-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=fbe31b3aa194bcd7047fbed2c3622b61b2eff8ac69caf495
     or http://127.0.0.1:8888/?token=fbe31b3aa194bcd7047fbed2c3622b61b2eff8ac69caf495
[W 13:36:41.950 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20210513133637 (::1) 10.890000ms referer=http://localhost:8888/notebooks/intro-ts-ai/lesson1.ipynb
**[I 13:36:41.987 NotebookApp] Kernel started: 73372fae-beba-497a-85af-ae8e8294be61, name: python3** 
```
