### ISSUE TITLE
Filter base on kernel type

### ISSUE THREAD

**Issue by fcollonval** [Anaconda-Platform/nb_conda_kernels#95]
The new capacity introduced in #80 has an annoying side effect with [ipywidgets](https://github.com/jupyter-widgets/ipywidgets). Indeed that technology uses a parallel Python kernel that should not be exposed in the notebook.

What is the best strategy to achieve that:
- Hard coded filtering
- Additional configurable filter for kernel type with default value `["ipywidgets" ]`

**Comment by mcg1969** [comment]
Can you please be more specific about what's going on here? What behavior do you expect, and what behavior are you seeing? How can I reproduce the issue?

**Comment by fcollonval** [comment]
I cannot reproduce the issue I got. I messed up something with the installed kernels. Sorry about that.
So I close this, as the feature I was talking about is not a priority for me. 

Nota: The idea would be to specify a set of kernel types that are allowed. For example, Python and R will be allowed but not JS or Haskell.
This can probably achieve through some elaborate `env_filter` specification.
