### ISSUE TITLE
nb_conda_kernels 2.2.0 not available?

### ISSUE THREAD

**Issue by harsham05** [Anaconda-Platform/nb_conda_kernels#98]
I was unable to find version 2.2.0 on https://anaconda.org/search?q=nb_conda_kernels

As per the changelog in the README, latest version is 2.2.0

```
$ conda install nb_conda_kernels==2.2.0 -c conda-forge
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - nb_conda_kernels==2.2.0
```

**Comment by mcg1969** [comment]
We have not tagged a release yet.

**Comment by willirath** [comment]
Is there any time-frame for a release?  Having #80 would be much appreciated.

**Comment by mcg1969** [comment]
Thanks for the ping. I'll work on it this weekend. But note you are free to add the `jupycon/label/dev` channel to the top of your channel list and update to use it now.
